knpu_oauth2_client:
    clients:
        facebook:
            # this will be one of the supported types
            type: facebook
            client_id: '%env(OAUTH_FACEBOOK_ID)%'
            client_secret: '%env(OAUTH_FACEBOOK_SECRET)%'
            # the route that you're redirected to after
            # see the controller example below
            redirect_route: auth.social.connect.check
            redirect_params: {type: '%env(OAUTH_FACEBOOK_TYPE)%' }
            graph_api_version: v2.12
        google:
            type: google
            client_id: '%env(OAUTH_GOOGLE_CLIENT_ID)%'
            client_secret: '%env(OAUTH_GOOGLE_CLIENT_SECRET)%'
            redirect_route: auth.social.connect.check
            redirect_params: {type: '%env(OAUTH_GOOGLE_TYPE)%' }