swiftmailer:
   transport:        gmail
   username:         '%env(MAILER_LOGIN)%'
   password:         '%env(MAILER_PASSWORD)%'
   host:             '%env(HOST_NAME)%'
   port:             465
   encryption:       ssl
   auth-mode:        login
   stream_options:
       ssl:
           allow_self_signed: true
           verify_peer: false
           verify_peer_name: false

#swiftmailer:
#    transport: smtp
#    username: '%env(MAILER_LOGIN)%'
#    password: '%env(MAILER_PASSWORD)%'
#    host: 'smtp.gmail.com'
#    port: 587
#    encryption: tls
#    auth-mode: login
#    stream_options:
#        ssl:
#            allow_self_signed: true
#            verify_peer: false
#            verify_peer_name: false
